#include "usb_protocol.h"
#include <string.h>
static void wr16(uint8_t*p,uint16_t v){p[0]=(uint8_t)v;p[1]=(uint8_t)(v>>8);}
static void wr32(uint8_t*p,uint32_t v){p[0]=(uint8_t)v;p[1]=(uint8_t)(v>>8);p[2]=(uint8_t)(v>>16);p[3]=(uint8_t)(v>>24);}
static uint16_t rd16(const uint8_t*p){return (uint16_t)p[0]|((uint16_t)p[1]<<8);}
static uint32_t rd32(const uint8_t*p){return (uint32_t)p[0]|((uint32_t)p[1]<<8)|((uint32_t)p[2]<<16)|((uint32_t)p[3]<<24);}
uint32_t usb_crc32(const uint8_t*data,size_t n){uint32_t c=0xFFFFFFFFu;if(!data&&n)return 0;for(size_t i=0;i<n;i++){c^=data[i];for(unsigned b=0;b<8;b++)c=(c&1u)?(c>>1)^0xEDB88320u:c>>1;}return c^0xFFFFFFFFu;}
static uint32_t packet_crc(const uint8_t *buf,size_t n){uint8_t tmp[USB_PROTO_MAX_PACKET];if(n>sizeof(tmp))return 0;memcpy(tmp,buf,n);memset(tmp+12,0,4);return usb_crc32(tmp,n);}
int usb_packet_encode(uint8_t*out,size_t cap,uint8_t cmd,uint32_t seq,const uint8_t*payload,uint16_t n,size_t*written){if(!out||!written||(!payload&&n)||n>USB_PROTO_MAX_PAYLOAD||cap<USB_PROTO_HEADER_SIZE+(size_t)n)return -1;wr32(out,USB_PROTO_MAGIC);out[4]=USB_PROTO_VERSION;out[5]=cmd;wr16(out+6,n);wr32(out+8,seq);wr32(out+12,0);if(n)memcpy(out+USB_PROTO_HEADER_SIZE,payload,n);wr32(out+12,packet_crc(out,USB_PROTO_HEADER_SIZE+n));*written=USB_PROTO_HEADER_SIZE+n;return 0;}
usb_status_t usb_packet_decode(const uint8_t*buf,size_t len,usb_packet_view_t*p){if(!buf||!p||len<USB_PROTO_HEADER_SIZE)return USB_STATUS_BAD_LENGTH;if(rd32(buf)!=USB_PROTO_MAGIC)return USB_STATUS_BAD_MAGIC;if(buf[4]!=USB_PROTO_VERSION)return USB_STATUS_BAD_VERSION;uint16_t n=rd16(buf+6);if(n>USB_PROTO_MAX_PAYLOAD||len!=USB_PROTO_HEADER_SIZE+(size_t)n)return USB_STATUS_BAD_LENGTH;if(packet_crc(buf,len)!=rd32(buf+12))return USB_STATUS_INTERNAL;p->version=buf[4];p->command=buf[5];p->payload_len=n;p->sequence=rd32(buf+8);p->crc32=rd32(buf+12);p->payload=buf+USB_PROTO_HEADER_SIZE;return USB_STATUS_OK;}
size_t usb_handle_command(const usb_packet_view_t*r,uint8_t*out,size_t cap,usb_counters_t*c){if(!r||!out||!c||cap<USB_PROTO_HEADER_SIZE)return 0;uint8_t payload[USB_PROTO_MAX_PAYLOAD];uint16_t n=0;usb_status_t status=USB_STATUS_OK;c->rx_packets++;switch(r->command){case USB_CMD_PING:if(r->payload_len)status=USB_STATUS_BAD_LENGTH;break;case USB_CMD_GET_INFO:{const char info[]="USB-CTRL;proto=1;bulk-out=1;bulk-in=129";n=(uint16_t)(sizeof(info)-1);memcpy(payload,info,n);break;}case USB_CMD_ECHO:n=r->payload_len;if(n)memcpy(payload,r->payload,n);break;case USB_CMD_GET_COUNTERS:memcpy(payload,c,sizeof(*c));n=(uint16_t)sizeof(*c);break;case USB_CMD_RESET_COUNTERS:if(r->payload_len)status=USB_STATUS_BAD_LENGTH;else memset(c,0,sizeof(*c));break;default:status=USB_STATUS_BAD_COMMAND;c->command_errors++;break;}if(status!=USB_STATUS_OK){payload[0]=(uint8_t)status;n=1;}size_t out_len=0;if(usb_packet_encode(out,cap,(uint8_t)(r->command|0x80u),r->sequence,payload,n,&out_len)!=0)return 0;c->tx_packets++;return out_len;}
